### ISSUE TITLE
Error during continuous use soapypower and Airspy

### ISSUE THREAD

**Issue by tavi343** [xmikos/simplesoapy#6]
I've running a little script to get 15min continuous data from an Airspy R2 device, at HF-UHF frequencies. The system is Ubuntu 18.04 on a HP Stream netbook. 

I don't know why I get this errors, time to time, after 2-5 days the entire script stopped:

> Traceback (most recent call last):
  File "/home/solar/anaconda3/bin/soapy_power", line 10, in <module>
    sys.exit(main())
  File "/home/solar/anaconda3/lib/python3.7/site-packages/soapypower/__main__.py", line 373, in main
    max_threads=args.max_threads, max_queue_size=args.max_queue_size
  File "/home/solar/anaconda3/lib/python3.7/site-packages/soapypower/power.py", line 296, in sweep
    psd_future, acq_time_start, acq_time_stop = self.psd(freq)
  File "/home/solar/anaconda3/lib/python3.7/site-packages/soapypower/power.py", line 256, in psd
    self.device.read_stream_into_buffer(self._buffer)
  File "/home/solar/anaconda3/lib/python3.7/site-packages/simplesoapy.py", line 484, in read_stream_into_buffer
    res.ret, SoapySDR.errToStr(res.ret)
RuntimeError: Unhandled readStream() error: -1 (TIMEOUT)

> 
Everything was downloaded and compiled locally on the machine. I've changed the USB cable, checked the connection with the server where the data is actually saved.

**Comment by wsnel** [comment]
I'm experiencing the exact same error, however consistently and immediately upon startup with an rtl-sdr device. When I, instead, use a Funcube dongle pro plus device, everything works as expected. I'm running on a Raspberry Pi.
